config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, only: [:destroy, :new, :show, :create] do
    resources :comments, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :child_comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: :Comment,
  inverse_of: :parent

  belongs_to :parent,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: :Comment,
  optional: true,
  inverse_of: :child_comments



end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  has_many :comments
  has_many :subbings
  has_many :subs, through: :subbings
  # belongs_to :subs
  # has_many :subs, through:
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sub < ApplicationRecord
  validates :name, :user_id, presence: true
  belongs_to :user
  has_many :subbings
  has_many :posts, through: :subbings
  # has_many :posts,
  # through:
end

app/models/subbing.rb
# == Schema Information
#
# Table name: subbings
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subbing < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :subs
  has_many :posts
  has_many :comments
  
  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def self.gen_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_token
    self.session_token = User.gen_token
    self.save
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    u = User.find_by(username: username)
    return nil if u.nil?
    return u if u.is_password?(password)
    nil
  end

  private

  def ensure_session_token
    self.session_token ||= User.gen_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_token
  end

  def logout
    current_user.reset_token
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    return nil unless current_user
    session[:session_token] == current_user.session_token
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new

  end

  def show
    @comment = Comment.find_by(id: params[:id])
    # fail
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    @comment.parent_comment_id = params[:parent_comment_id] if params[:parent_comment_id]
    # fail
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    #how do I redirect back to the post? Without using @comment object
    post = Post.find_by(id: params[:post_id])
    redirect_to post_url(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    # fail
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_ids = params[:post][:sub_ids]
    # fail
    if @post.save
      # fail
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])

  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy
    redirect_to sub_url(post.sub_id)
  end
  private

  def post_params
    params.require(:post).permit(:title, :body, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["bad login"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in
  def index
    @subs = Sub.all
  end

  def new
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
New Comment
<form action="<%= post_comments_url %>" method="post">
  Body<input type="text" name="comment[body]" value="">
  <input type="submit" value="Create Comment">
</form>

app/views/comments/show.html.erb
<%= @comment.body %>

Reply to comment

<form action="<%= post_comments_url %>" method="post">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  Body<input type="text" name="comment[body]" value="">
  <input type="submit" value="Reply">
</form>

app/views/layouts/_comments.html.erb
<ul>
<% comment.child_comments.each do |child| %>
  <li><%= child.body %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      Logged in as: <%= current_user.username %>
      <%= button_to "Logout", session_url, method: :delete %>
      <a href="<%= subs_url %>">Subs Index</a>

    <br>
    <% end %>
    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <br><%= error %><br>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
New post
<form action="<%= posts_url %>" method="post">
  title<input type="text" name="post[title]" value="">
  body<input type="text" name="post[body]" value="">
  <br>Post to which subs?<br>
  <% Sub.all.each do |sub| %>
    <input
      type="checkbox"
      name="post[sub_ids][]"
      value="<%= sub.id %>"><%= sub.name %><br>
  <%  end %>
  <input type="submit" value="Create Post">
</form>

<!-- checkboxes for all subs  -->

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.body %><br>
<hr>
<!-- DOES NOT WORK see childrecursion.rb in root directory for an example of
how to recursively output children comments  -->
Comments<br>
<% @post.comments.each do |comment| %>
  <%= comment.body %>
  <% comment.child_comments.each do |child| %>
    <%= render 'layouts/comments', comment: comment %>
  <% end %>
<% end %>

<%= button_to "Add Comment", new_post_comment_url(@post), method: :get %>

app/views/subs/edit.html.erb
Edit Sub
<form action="<%= subs_url %>" method="post">
  Sub name<input type="text" name="sub[name]" value="<%= @sub.name %>">
  <input type="submit" value="Create Sub">
</form>

app/views/subs/index.html.erb
Subs Index<br>
<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><%= sub.name %></a><br>
<% end %>

app/views/subs/new.html.erb
New Sub
<form action="<%= subs_url %>" method="post">
  Sub name<input type="text" name="sub[name]" value="">
  <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<a href="<%= subs_url %>">Back to index</a><br>
Sub: <%= @sub.name %>
(Created by <%= @sub.user.username %>) <br>
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a><br>

<% @sub.posts.each do |post| %>
  <a href="<%= post_url(post) %>"> <%= post.title %></a> <br>
<% end %>

<%= button_to "New Post", new_post_url(@sub), method: :get %>

app/views/users/new.html.erb
New User
<form action="<%= users_url %>" method="post">
  Username<input type="text" name="user[username]" value="">
  Password<input type="text" name="user[password]" value="">
  <input type="submit" value="Create User">
</form>